# Generated by Django 5.2.6 on 2025-09-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0003_client_tender_client_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='client',
        ),
    ]
